### ISSUE TITLE
Textarea looks weird

### ISSUE THREAD

**Issue by velosipedist** [4xxi/caesarapp-web-client#2]
## Expected Behavior
Textarea fits text inside and layout column width

## Actual Behavior
Textarea is shrinked horizontally to be very narrow

## Steps to Reproduce the Problem

  1. Go to any valid caesar app link with encrypted text area
  1. Look for textarea under Secret Text label

Vivaldi 1.11.917.43

**Comment by beshkenadze** [comment]
Here is the screenshot.
![image](https://user-images.githubusercontent.com/167288/30282352-b78613de-971d-11e7-8f05-d81ff9769372.png)
