### ISSUE TITLE
Limit Dropdown and File Placeholder intersection

### ISSUE THREAD

**Issue by mkuznetsov4xxi** [4xxi/caesarapp-web-client#3]
## Expected Behavior
http://scr.4xxi.com/mk/VENI_VIDI_ENCRYPTED__2017-09-11_18-36-27.jpg

## Actual Behavior
http://scr.4xxi.com/mk/VENI_VIDI_ENCRYPTED__2017-09-11_18-34-14.jpg

## Steps to Reproduce the Problem

  1. Resize browser screen height to 800px.
  2. Click on dropbox with limits.

## Specifications

  - Platform: MacOsX 10.12.5
  - Subsystem: Chrome browser

**Comment by beshkenadze** [comment]
Fixed in 53a6686
